# Introduction
Before passing data into numpy or tensor, etc. We read data using Pandas from CSV files.
Some variables might need to convert from string to number, e.g. float, int, etc.
If we don't won't convert string into dummy variables, cause dummy variables might increase the number of variables.
Thus, we can use below ways to do so which are not using "pd.to_dummy"

# Read Raw Dataset and Store as DataFrame

In [1]:
import pandas as pd
df = pd.read_csv(r"./Datasets/Iris.csv")
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

# Method 1: Map
**Really Not Recommended**
1. Manual type in the elements name and indicate their numerical number, might cause error.
2. If variable contains tons of different type of elements, the workload will be horrible.
3. Not easy to convert enumerate type back to it original name. E.g. After training AI/ML model, we might need to convert enumerate type variables back to it original type.

In [2]:
df1 = df.copy()
variety_dic = {"Setosa": 0,
               "Versicolor": 1,
               "Virginica": 2}
df1["variety"] = df1["variety"].map(variety_dic)
df1

     sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

# Method 2: Factorize
**Recommended**
1. Automatic encode the object as an enumerated type or categorical variable.
2. No manual errors.
3. Easy to reverse convertion process.

## Factorizing

In [10]:
df2 = df.copy()
code, uniques = pd.factorize(df2["variety"])
df2["variety"] = code
df2

     sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

## Reverse Factorize

In [11]:
original_variety = uniques[code]
original_variety, uniques, uniques[0],uniques[1], uniques[2]

(Index(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
        'Setosa', 'Setosa', 'Setosa',
        ...
        'Virginica', 'Virginica', 'Virginica', 'Virginica', 'Virginica',
        'Virginica', 'Virginica', 'Virginica', 'Virginica', 'Virginica'],
       dtype='object', length=150),
 Index(['Setosa', 'Versicolor', 'Virginica'], dtype='object'),
 'Setosa',
 'Versicolor',
 'Virginica')